/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Forms;

import Clases.menu;
import Clases.listenerPer;
import Clases.metodosPer;
import Conexion.traducSQL;
import Estructuras.proveedores;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.QUESTION_MESSAGE;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import static javax.swing.JOptionPane.showConfirmDialog;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.dbutils.handlers.BeanListHandler;
/**
 *
 * @author Daniel Marcucci
 */
public class crudpro1 extends javax.swing.JFrame {
    private List<proveedores> listaPro;
    traducSQL ejSQL = new traducSQL();
    menu menu = new menu();
    metodosPer mp = new metodosPer();
    public crudpro1() {
        initComponents();
        menu.propList(listMenu);
        
        listenerPer l = new listenerPer();
        txtNit.addKeyListener(l.keyNext);
        chbEstado.addKeyListener(l.keyNext);
        txtNom.addKeyListener(l.keyNext);
        txtDir.addKeyListener(l.keyNext);
        txtTel.addKeyListener(l.keyNext);
        txtContac.addKeyListener(l.keyNext);
        txtCorreo.addKeyListener(l.keyNext);
        
        btnGuardar.addKeyListener(l.keyPress);
        btnEliminar.addKeyListener(l.keyPress);
        btnNuevo.addKeyListener(l.keyPress);
        
        ButtonGroup bgBuscar = new ButtonGroup();
        bgBuscar.add(rdNit);
        bgBuscar.add(rdNom);
        bgBuscar.add(rdDir);
        
        txtNit.requestFocus();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUsu = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNit = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        txtDir = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        chbEstado = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        txtContac = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBusPro = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Desabilitar celdas editables
            }
        };
        txtBusPro = new javax.swing.JTextField();
        btnBusPro = new javax.swing.JButton();
        rdNit = new javax.swing.JRadioButton();
        rdNom = new javax.swing.JRadioButton();
        rdDir = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        listMenu = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 7, 13));

        jPanel2.setBackground(new java.awt.Color(0, 16, 28));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 182, 255));
        jLabel1.setText("Proveedores");

        lblUsu.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblUsu.setForeground(new java.awt.Color(0, 182, 255));
        lblUsu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsu.setText("Usuario");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 16, 28));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 182, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("NIT");

        txtNit.setBackground(new java.awt.Color(0, 182, 255));
        txtNit.setForeground(new java.awt.Color(0, 0, 0));
        txtNit.setDisabledTextColor(new java.awt.Color(0, 182, 255));
        txtNit.setSelectionColor(new java.awt.Color(204, 204, 204));
        txtNit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNitFocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 182, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nombre");

        txtNom.setBackground(new java.awt.Color(0, 182, 255));
        txtNom.setForeground(new java.awt.Color(0, 0, 0));

        txtDir.setBackground(new java.awt.Color(0, 182, 255));
        txtDir.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 182, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Dirección");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 182, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Teléfono");

        txtTel.setBackground(new java.awt.Color(0, 182, 255));
        txtTel.setForeground(new java.awt.Color(0, 0, 0));

        btnGuardar.setBackground(new java.awt.Color(0, 187, 0));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(0, 173, 0));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Guardar.png"))); // NOI18N
        btnGuardar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(204, 0, 0));
        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 51, 0));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Eliminar.png"))); // NOI18N
        btnEliminar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnEliminar.setBorderPainted(false);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnNuevo.setBackground(new java.awt.Color(1, 176, 110));
        btnNuevo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(0, 193, 120));
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Nuevo.png"))); // NOI18N
        btnNuevo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnNuevo.setBorderPainted(false);
        btnNuevo.setContentAreaFilled(false);
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        chbEstado.setBackground(new java.awt.Color(0, 117, 197));
        chbEstado.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        chbEstado.setForeground(new java.awt.Color(0, 182, 255));
        chbEstado.setSelected(true);
        chbEstado.setText("Estado");
        chbEstado.setContentAreaFilled(false);
        chbEstado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chbEstado.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 182, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Contacto");

        txtContac.setBackground(new java.awt.Color(0, 182, 255));
        txtContac.setForeground(new java.awt.Color(0, 0, 0));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 182, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Correo");

        txtCorreo.setBackground(new java.awt.Color(0, 182, 255));
        txtCorreo.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtContac, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(txtNit, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                                        .addComponent(chbEstado))
                                    .addComponent(txtDir)
                                    .addComponent(txtNom))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtCorreo)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNuevo)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtContac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(0, 16, 28));

        tblBusPro.setBackground(new java.awt.Color(0, 30, 51));
        tblBusPro.setForeground(new java.awt.Color(255, 255, 255));
        tblBusPro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nit", "Nombre"
            }
        ));
        tblBusPro.setSelectionBackground(new java.awt.Color(0, 7, 13));
        tblBusPro.setSelectionForeground(new java.awt.Color(0, 182, 255));
        tblBusPro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBusProMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBusPro);
        if (tblBusPro.getColumnModel().getColumnCount() > 0) {
            tblBusPro.getColumnModel().getColumn(0).setMinWidth(150);
            tblBusPro.getColumnModel().getColumn(0).setPreferredWidth(150);
            tblBusPro.getColumnModel().getColumn(0).setMaxWidth(150);
        }

        txtBusPro.setBackground(new java.awt.Color(0, 182, 255));
        txtBusPro.setForeground(new java.awt.Color(0, 0, 0));

        btnBusPro.setBackground(new java.awt.Color(0, 162, 227));
        btnBusPro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBusPro.setForeground(new java.awt.Color(0, 182, 255));
        btnBusPro.setText("Buscar");
        btnBusPro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnBusPro.setContentAreaFilled(false);
        btnBusPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusProActionPerformed(evt);
            }
        });

        rdNit.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        rdNit.setForeground(new java.awt.Color(0, 182, 255));
        rdNit.setSelected(true);
        rdNit.setText("NIT");
        rdNit.setContentAreaFilled(false);

        rdNom.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        rdNom.setForeground(new java.awt.Color(0, 182, 255));
        rdNom.setText("Nombre");
        rdNom.setContentAreaFilled(false);

        rdDir.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        rdDir.setForeground(new java.awt.Color(0, 182, 255));
        rdDir.setText("Dirección");
        rdDir.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(rdNit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdNom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdDir)
                        .addGap(0, 124, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnBusPro, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBusPro)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdNit)
                    .addComponent(rdNom)
                    .addComponent(rdDir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBusPro, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBusPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(0, 16, 28));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 182, 255));
        jLabel9.setText("© Nombre");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap())
        );

        listMenu.setBackground(new java.awt.Color(0, 16, 28));
        listMenu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        listMenu.setForeground(new java.awt.Color(255, 255, 255));
        listMenu.setSelectionBackground(new java.awt.Color(255, 255, 255));
        listMenu.setSelectionForeground(new java.awt.Color(0, 56, 94));
        listMenu.setVisibleRowCount(4);
        listMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listMenuMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(listMenu);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 248, Short.MAX_VALUE))
                            .addComponent(jScrollPane7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (validarBtn()==false) {
            return;
        }
        String iqr, uqr;
        Object[] ivl, uvl;
        iqr = "INSERT INTO proveedores(nitProPadre,nom,dir,tel,contac,correo,estado) VALUES(?,?,?,?,?,?,?)";
        ivl = new Object[]{txtNit.getText(),txtNom.getText(),txtDir.getText(),txtTel.getText(),txtContac.getText(),txtCorreo.getText(),chbEstado.isSelected()};
        uqr = "UPDATE proveedores SET nom=?,dir=?,tel=?,contac=?,correo=?,estado=? WHERE nitProPadre=?";
        uvl = new Object[]{txtNom.getText(),txtDir.getText(),txtTel.getText(),txtContac.getText(),txtCorreo.getText(),chbEstado.isSelected(),txtNit.getText()};
        ejSQL.insertUpdate(iqr, ivl, uqr, uvl);
        limpiarBtn(true);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if(validarBtn()==false){
            return;
        }
        String eqr;
        Object[] evl;
        if(YES_NO_OPTION == showConfirmDialog(null,"¿Está seguro de querer eliminar este registro?","Eliminar Registro",YES_NO_OPTION,QUESTION_MESSAGE)){
            eqr = "DELETE FROM proveedores WHERE nitProPadre=?";
            evl = new Object[]{txtNit.getText()};
            limpiarBtn(ejSQL.delete(eqr,evl));
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBusProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusProActionPerformed
        int rd;
        if(rdNit.isSelected()){
            rd=1;
        } else if(rdNom.isSelected()){
            rd=2;
        } else {
            rd=3;
        }
        listaPro = bPro(tblBusPro, txtBusPro.getText(), rd);
    }//GEN-LAST:event_btnBusProActionPerformed

    private void tblBusProMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBusProMouseClicked
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            bProSele(tblBusPro);
        }
    }//GEN-LAST:event_tblBusProMouseClicked

    private void listMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMenuMouseClicked
        menu.opciones(evt, this, listMenu);
    }//GEN-LAST:event_listMenuMouseClicked

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        limpiarBtn(false);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void txtNitFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNitFocusLost
        rPro();
    }//GEN-LAST:event_txtNitFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crudpro1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crudpro1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crudpro1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crudpro1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new crudpro1().setVisible(true);
            }
        });
    }
    
    // <editor-fold defaultstate="collapsed" desc="Métodos">
    // <editor-fold defaultstate="collapsed" desc="validarBtn">
    public boolean validarBtn(){
        if(txtNit.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Es necesario ingresar un código");
            txtNit.requestFocus();
            return false;
        }
        return true;
    }
    // </editor-fold>
    // <editor-fold defaultstate="collapsed" desc="limpiarBtn">
    public void limpiarBtn(boolean btn){
        txtNit.setText("");
        txtNom.setText("");
        txtDir.setText("");
        txtTel.setText("");
        txtContac.setText("");
        txtCorreo.setText("");
        chbEstado.setSelected(true);
        if (btn) {
           try {
                listaPro.clear();
            } catch(NullPointerException e){
                System.out.println("Se evitó el error .clear(): "+e);
            }
            mp.tblVaciar(tblBusPro);
        }
        mp.txtEnabled(txtNit);
        txtNit.requestFocus();
    }
    // </editor-fold>
    // <editor-fold defaultstate="collapsed" desc="bProSele">
    private void bProSele(JTable tabla) {
        try {
            int row = tabla.getSelectedRow();
            if (row < 0) {
                row = 0;
            }
            txtNit.setText(listaPro.get(row).getNitProPadre());
            txtNom.setText(listaPro.get(row).getNom());
            txtDir.setText(listaPro.get(row).getDir());
            txtTel.setText(listaPro.get(row).getTel());
            txtContac.setText(listaPro.get(row).getContac());
            txtCorreo.setText(listaPro.get(row).getCorreo());
            if (listaPro.get(row).isEstado()){
                chbEstado.setSelected(true);
            } else {
                chbEstado.setSelected(false);
            }
            mp.txtDisabled(txtNit);
        } catch (Exception ex) {
            showMessageDialog(null,"Error: "+ex);
        }
    }
    // </editor-fold>
    // <editor-fold defaultstate="collapsed" desc="bPro">
    public List bPro(JTable tbl,String texto,int opc){
        String[] columnas = new String[2];
        DefaultTableModel filas = (DefaultTableModel) tbl.getModel();
        BeanListHandler blh = new BeanListHandler(proveedores.class);
        Object[] vl = new Object[]{};
        List<proveedores> listaF = ejSQL.select("SELECT * FROM proveedores", blh, vl);
        if("".equals(texto)){
            listaF = listaF.stream()
                    .collect(Collectors.toList());
        }else{
            switch (opc) {
                case 1:
                    listaF = (List<proveedores>) listaF.stream()
                            .filter(c -> (c.getNitProPadre().toUpperCase()).contains((texto.toUpperCase())))
                            .collect(Collectors.toList());
                    break;
                case 2:
                    listaF = (List<proveedores>) listaF.stream()
                            .filter(c -> (c.getNom().toUpperCase()).contains((texto.toUpperCase())))
                            .collect(Collectors.toList());
                    break;
                default:
                    listaF = (List<proveedores>) listaF.stream()
                            .filter(c -> (c.getDir().toUpperCase()).contains((texto.toUpperCase())))
                            .collect(Collectors.toList());
                    break;
            }
        }
        listaF.forEach(item->{
            columnas[0]=item.getNitProPadre();
            columnas[1]=item.getNom();
            filas.addRow(columnas);
        });
        tbl.setModel(filas);
        return listaF;
    }
    // </editor-fold>
    // <editor-fold defaultstate="collapsed" desc="rPro">
    public void rPro(){
        String qr;
        Object[] vl;
        if(txtNit.getText().isEmpty()){
            return;
        }
        qr = "SELECT * FROM proveedores WHERE nitProPadre=?";
        vl = new Object[]{txtNit.getText()};
        BeanListHandler blh = new BeanListHandler(proveedores.class);
        List<proveedores> lArt = ejSQL.select(qr, blh, vl);
        
        if(lArt.isEmpty()){
            mp.txtEnabled(txtNit);
            return;
        }
        
        lArt.forEach(item->{
            txtNit.setText(item.getNitProPadre());
            txtNom.setText(item.getNom());
            txtDir.setText(item.getDir());
            txtTel.setText(item.getTel());
            txtContac.setText(item.getContac());
            txtCorreo.setText(item.getCorreo());
            if (item.isEstado()){
                chbEstado.setSelected(true);
            } else {
                chbEstado.setSelected(false);
            }
        });
        
        mp.txtDisabled(txtNit);
    }
    // </editor-fold>
    // </editor-fold>

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBusPro;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JCheckBox chbEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lblUsu;
    private javax.swing.JList<String> listMenu;
    private javax.swing.JRadioButton rdDir;
    private javax.swing.JRadioButton rdNit;
    private javax.swing.JRadioButton rdNom;
    private javax.swing.JTable tblBusPro;
    private javax.swing.JTextField txtBusPro;
    private javax.swing.JTextField txtContac;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDir;
    private javax.swing.JTextField txtNit;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables

}
