/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Forms;

import Clases.menu;
import Clases.listenerPer;
import Clases.metodosPer;
import Conexion.traducSQL;
import Estructuras.articulos;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.QUESTION_MESSAGE;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import static javax.swing.JOptionPane.showConfirmDialog;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.dbutils.handlers.BeanListHandler;
/**
 *
 * @author Daniel Marcucci
 */
public class crudart1 extends javax.swing.JFrame {
    private List<articulos> listaArt;
    traducSQL ejSQL = new traducSQL();
    menu menu = new menu();
    metodosPer mp = new metodosPer();
    public crudart1() {
        initComponents();
        menu.propList(listMenu);
        
        listenerPer l = new listenerPer();
        txtCod.addKeyListener(l.keyNext);
        chbEstado.addKeyListener(l.keyNext);
        txtDes.addKeyListener(l.keyNext);
        
        l.txtInt(txtId);
        
        l.txtDouble(txtPreVenta);
        l.txtDouble(txtPreCosto);
        
        btnGuardar.addKeyListener(l.keyPress);
        btnEliminar.addKeyListener(l.keyPress);
        btnNuevo.addKeyListener(l.keyPress);
        
        ButtonGroup bgBuscar = new ButtonGroup();
        bgBuscar.add(rdCod);
        bgBuscar.add(rdDes);
        
        txtId.requestFocus();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUsu = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDes = new javax.swing.JTextField();
        txtPreVenta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPreCosto = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        chbEstado = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBusArt = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Desabilitar celdas editables
            }
        };
        txtBusArt = new javax.swing.JTextField();
        btnBusArt = new javax.swing.JButton();
        rdCod = new javax.swing.JRadioButton();
        rdDes = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        listMenu = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 7, 13));

        jPanel2.setBackground(new java.awt.Color(0, 16, 28));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 182, 255));
        jLabel1.setText("Artículos");

        lblUsu.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblUsu.setForeground(new java.awt.Color(0, 182, 255));
        lblUsu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsu.setText("Usuario");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblUsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 16, 28));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 182, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Código");

        txtCod.setBackground(new java.awt.Color(0, 182, 255));
        txtCod.setForeground(new java.awt.Color(0, 0, 0));
        txtCod.setDisabledTextColor(new java.awt.Color(0, 182, 255));
        txtCod.setSelectionColor(new java.awt.Color(204, 204, 204));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 182, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Descripción");

        txtDes.setBackground(new java.awt.Color(0, 182, 255));
        txtDes.setForeground(new java.awt.Color(0, 0, 0));

        txtPreVenta.setBackground(new java.awt.Color(0, 182, 255));
        txtPreVenta.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 182, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Precio Venta");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 182, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Precio Costo");

        txtPreCosto.setBackground(new java.awt.Color(0, 182, 255));
        txtPreCosto.setForeground(new java.awt.Color(0, 0, 0));

        btnGuardar.setBackground(new java.awt.Color(0, 187, 0));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(0, 173, 0));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Guardar.png"))); // NOI18N
        btnGuardar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(204, 0, 0));
        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 51, 0));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Eliminar.png"))); // NOI18N
        btnEliminar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnEliminar.setBorderPainted(false);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnNuevo.setBackground(new java.awt.Color(1, 176, 110));
        btnNuevo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(0, 193, 120));
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Nuevo.png"))); // NOI18N
        btnNuevo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnNuevo.setBorderPainted(false);
        btnNuevo.setContentAreaFilled(false);
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        chbEstado.setBackground(new java.awt.Color(0, 117, 197));
        chbEstado.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        chbEstado.setForeground(new java.awt.Color(0, 182, 255));
        chbEstado.setSelected(true);
        chbEstado.setText("Estado");
        chbEstado.setContentAreaFilled(false);
        chbEstado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chbEstado.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 182, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("ID");

        txtId.setBackground(new java.awt.Color(0, 182, 255));
        txtId.setForeground(new java.awt.Color(0, 0, 0));
        txtId.setDisabledTextColor(new java.awt.Color(0, 182, 255));
        txtId.setSelectionColor(new java.awt.Color(204, 204, 204));
        txtId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chbEstado))
                    .addComponent(txtDes, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtPreVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPreCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNuevo)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbEstado)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPreVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtPreCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(0, 16, 28));

        tblBusArt.setBackground(new java.awt.Color(0, 30, 51));
        tblBusArt.setForeground(new java.awt.Color(255, 255, 255));
        tblBusArt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Código", "Descripción"
            }
        ));
        tblBusArt.setSelectionBackground(new java.awt.Color(0, 7, 13));
        tblBusArt.setSelectionForeground(new java.awt.Color(0, 182, 255));
        tblBusArt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBusArtMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBusArt);
        if (tblBusArt.getColumnModel().getColumnCount() > 0) {
            tblBusArt.getColumnModel().getColumn(0).setMinWidth(100);
            tblBusArt.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblBusArt.getColumnModel().getColumn(0).setMaxWidth(100);
            tblBusArt.getColumnModel().getColumn(1).setMinWidth(150);
            tblBusArt.getColumnModel().getColumn(1).setPreferredWidth(150);
            tblBusArt.getColumnModel().getColumn(1).setMaxWidth(150);
        }

        txtBusArt.setBackground(new java.awt.Color(0, 182, 255));
        txtBusArt.setForeground(new java.awt.Color(0, 0, 0));

        btnBusArt.setBackground(new java.awt.Color(0, 162, 227));
        btnBusArt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBusArt.setForeground(new java.awt.Color(0, 182, 255));
        btnBusArt.setText("Buscar");
        btnBusArt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnBusArt.setContentAreaFilled(false);
        btnBusArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusArtActionPerformed(evt);
            }
        });

        rdCod.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        rdCod.setForeground(new java.awt.Color(0, 182, 255));
        rdCod.setSelected(true);
        rdCod.setText("Código");
        rdCod.setContentAreaFilled(false);

        rdDes.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        rdDes.setForeground(new java.awt.Color(0, 182, 255));
        rdDes.setText("Descripción");
        rdDes.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(rdCod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdDes)
                        .addGap(0, 146, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnBusArt, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBusArt)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdCod)
                    .addComponent(rdDes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBusArt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBusArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(0, 16, 28));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 182, 255));
        jLabel9.setText("© Nombre");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap())
        );

        listMenu.setBackground(new java.awt.Color(0, 16, 28));
        listMenu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        listMenu.setForeground(new java.awt.Color(255, 255, 255));
        listMenu.setSelectionBackground(new java.awt.Color(255, 255, 255));
        listMenu.setSelectionForeground(new java.awt.Color(0, 56, 94));
        listMenu.setVisibleRowCount(4);
        listMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listMenuMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(listMenu);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 249, Short.MAX_VALUE))
                            .addComponent(jScrollPane7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (validarBtn()==false) {
            return;
        }
        String iqr, uqr;
        Object[] ivl, uvl;
        iqr = "INSERT INTO articulos(idArtPadre,cod,des,preVenta,preCosto,estado) VALUES(?,?,?,?,?,?)";
        ivl = new Object[]{txtId.getText(),txtCod.getText(),txtDes.getText(),txtPreVenta.getText(),txtPreCosto.getText(),chbEstado.isSelected()};
        uqr = "UPDATE articulos SET des=?,preVenta=?,preCosto=?,estado=? WHERE cod=? AND idArtPadre=?";
        uvl = new Object[]{txtDes.getText(),txtPreVenta.getText(),txtPreCosto.getText(),chbEstado.isSelected(),txtCod.getText(),txtId.getText()};
        ejSQL.insertUpdate(iqr, ivl, uqr, uvl);
        
        limpiarBtn(true);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if(validarBtn()==false){
            return;
        }
        String eqr;
        Object[] evl;
        if(YES_NO_OPTION == showConfirmDialog(null,"¿Está seguro de querer eliminar este registro?","Eliminar Registro",YES_NO_OPTION,QUESTION_MESSAGE)){
            eqr = "DELETE FROM articulos WHERE cod=? AND idArtPadre=?";
            evl = new Object[]{txtCod.getText()};
            limpiarBtn(ejSQL.delete(eqr,evl));
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBusArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusArtActionPerformed
        int rd;
        if(rdCod.isSelected()){
            rd=1;
        } else if(rdDes.isSelected()){
            rd=2;
        } else {
            rd=3;
        }
        listaArt = bArt(tblBusArt, txtBusArt.getText(), rd);
    }//GEN-LAST:event_btnBusArtActionPerformed

    private void tblBusArtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBusArtMouseClicked
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            bArtSele(tblBusArt);
        }
    }//GEN-LAST:event_tblBusArtMouseClicked

    private void listMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMenuMouseClicked
        menu.opciones(evt, this, listMenu);
    }//GEN-LAST:event_listMenuMouseClicked

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        limpiarBtn(false);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void txtIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdFocusLost
        rArt();
    }//GEN-LAST:event_txtIdFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crudart1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crudart1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crudart1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crudart1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new crudart1().setVisible(true);
            }
        });
    }
    
    // <editor-fold defaultstate="collapsed" desc="Métodos">
    // <editor-fold defaultstate="collapsed" desc="validarBtn">
    public boolean validarBtn(){
        if(txtCod.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Es necesario ingresar un código");
            txtCod.requestFocus();
            return false;
        } else if(txtId.getText().equals("0")){
            JOptionPane.showMessageDialog(null, "Es necesario ingresar un ID que no sea '0'");
            txtId.requestFocus();
            return false;
        }
        return true;
    }
    // </editor-fold>
    // <editor-fold defaultstate="collapsed" desc="limpiarBtn">
    public void limpiarBtn(boolean btn){
        txtId.setText("0");
        txtCod.setText("");
        txtDes.setText("");
        txtPreVenta.setText("0.00");
        txtPreCosto.setText("0.00");
        chbEstado.setSelected(true);
        if (btn){
            try {
                listaArt.clear();
            } catch(NullPointerException e){
                System.out.println("Se evitó el error .clear(): "+e);
            }
            mp.tblVaciar(tblBusArt);
        }
        mp.txtEnabled(txtId);
        mp.txtEnabled(txtCod);
        txtId.requestFocus();
    }
    // </editor-fold>
    // <editor-fold defaultstate="collapsed" desc="bArtSele">
    private void bArtSele(JTable tabla) {
        try {
            int row = tabla.getSelectedRow();
            if (row < 0) {
                row = 0;
            }
            txtId.setText(String.valueOf(listaArt.get(row).getIdArtPadre()));
            txtCod.setText(listaArt.get(row).getCod());
            txtDes.setText(listaArt.get(row).getDes());
            txtPreVenta.setText(String.valueOf(listaArt.get(row).getPreVenta()));
            txtPreCosto.setText(String.valueOf(listaArt.get(row).getPreCosto()));
            if (listaArt.get(row).isEstado()){
                chbEstado.setSelected(true);
            } else {
                chbEstado.setSelected(false);
            }
            mp.txtDisabled(txtId);
        } catch (Exception ex) {
            showMessageDialog(null,"Error: "+ex);
        }
    }
    // </editor-fold>
    // <editor-fold defaultstate="collapsed" desc="bArt">
    public List bArt(JTable tbl,String texto,int opc){
        String[] columnas = new String[3];
        DefaultTableModel filas = (DefaultTableModel) tbl.getModel();
        BeanListHandler blh = new BeanListHandler(articulos.class);
        Object[] vl = new Object[]{};
        List<articulos> listaF = ejSQL.select("SELECT * FROM articulos", blh, vl);
        if("".equals(texto)){
            listaF = listaF.stream()
                    .collect(Collectors.toList());
        }else{
            switch (opc) {
                case 1:
                    listaF = (List<articulos>) listaF.stream()
                            .filter(c -> (c.getCod().toUpperCase()).contains((texto.toUpperCase())))
                            .collect(Collectors.toList());
                    break;
                default:
                    listaF = (List<articulos>) listaF.stream()
                            .filter(c -> (c.getDes().toUpperCase()).contains((texto.toUpperCase())))
                            .collect(Collectors.toList());
                    break;
            }
        }
        listaF.forEach(item->{
            columnas[0]=String.valueOf(item.getIdArtPadre());
            columnas[1]=item.getCod();
            columnas[2]=item.getDes();
            filas.addRow(columnas);
        });
        tbl.setModel(filas);
        return listaF;
    }
    // </editor-fold>
    // <editor-fold defaultstate="collapsed" desc="rArt">
    public void rArt(){
        if(txtId.getText().equals("0")){
            return;
        }
        String qr;
        Object[] vl;
        qr = "SELECT * FROM articulos WHERE idArtPadre=?";
        vl = new Object[]{txtId.getText()};
        BeanListHandler blh = new BeanListHandler(articulos.class);
        List<articulos> lArt = ejSQL.select(qr, blh, vl);
        
        if(lArt.isEmpty()){
            mp.txtEnabled(txtId);
            return;
        }
        
        lArt.forEach(item->{
            txtCod.setText(item.getCod());
            txtDes.setText(item.getDes());
            txtPreVenta.setText(String.valueOf(item.getPreVenta()));
            txtPreCosto.setText(String.valueOf(item.getPreCosto()));
            if (item.isEstado()){
                chbEstado.setSelected(true);
            } else {
                chbEstado.setSelected(false);
            }
        });
        
        mp.txtDisabled(txtId);
    }
    // </editor-fold>
    // </editor-fold>

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBusArt;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JCheckBox chbEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lblUsu;
    private javax.swing.JList<String> listMenu;
    private javax.swing.JRadioButton rdCod;
    private javax.swing.JRadioButton rdDes;
    private javax.swing.JTable tblBusArt;
    private javax.swing.JTextField txtBusArt;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtDes;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPreCosto;
    private javax.swing.JTextField txtPreVenta;
    // End of variables declaration//GEN-END:variables

}
